export const APP_ROUND_INCREMENT = "APP/ROUND_INCREMENT";
export const APP_ROUND_REMOVE = "APP/ROUND_REMOVE";
export const APP_CHOSE_BIRD = "APP/CHOSE_BIRD";
export const APP_ADD_UNKNOWN_BIRD = "APP/ADD_UNKNOWN_BIRD";
export const APP_CHOSEN_CORRECT_BIRD = "APP/CHOSEN_CORRECT_BIRD";
export const APP_ADD_SCORE = "APP/ADD_SCORE";
export const APP_ADD_ATTEMPTS = "APP/ADD_ATTEMPTS";
export const APP_REMOVE_SCORE = "APP/REMOVE_SCORE";
export const APP_REMOVE_ATTEMPTS = "APP/REMOVE_ATTEMPTS";
export const APP_CORRECT_ANSWER = "APP/CORRECT_ANSWER"
export const APP_INCORRECT_ANSWER = "APP/INCORRECT_ANSWER"
export const APP_REMOVE_ANSWERS ="APP/REMOVE_ANSWER"
export const APP_SHOW_MENU = "APP/SHOW_MENU"
export const APP_HIDE_MENU = "APP/HIDE_MENU"
export const APP_LIBRARY_SHOW_BIRD_LIST = "APP/LIBRARY/SHOW_BIRD_LIST"

